services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE:-disable}
      - JWT_SECRET=${JWT_SECRET}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_PRIVATE_KEY_ID=${GCP_PRIVATE_KEY_ID}
      - GCP_PRIVATE_KEY=${GCP_PRIVATE_KEY}
      - GCP_CLIENT_EMAIL=${GCP_CLIENT_EMAIL}
      - GCP_CLIENT_ID=${GCP_CLIENT_ID}
      - GCP_CLIENT_X509_CERT_URL=${GCP_CLIENT_X509_CERT_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - NODE_ENV=prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-resume-network

networks:
  ai-resume-network:
    external: true