package services

type seedEntry struct {
	Title    string
	Category string
	Content  string
}

var knowledgeSeedData = []seedEntry{
	// ── Product (15) ──────────────────────────────────────
	{"HiHired Pricing Plans", "product", "HiHired offers three plans. Free: 1 resume per week, basic templates, PDF export. Premium ($7.99/month, first month $1.99): 30 resumes/month, all templates, AI optimization, cover letters. Ultimate ($29.99/month): 200 resumes/month, priority support, advanced AI features, unlimited cover letters."},
	{"HiHired Platform Overview", "product", "HiHired is an AI-powered career platform that helps job seekers build professional resumes, match with relevant jobs, and prepare for interviews. Features include an AI resume builder, job matching with 35,000+ active postings, an AI career coach chatbot, application tracking, and one-click resume tailoring."},
	{"How to Use the Resume Builder", "product", "Step-by-step: 1) Import your existing resume or start fresh. 2) Fill in contact info, experience, education, skills, and projects. 3) Paste a job description to tailor your resume. 4) Click optimize to let AI improve your content. 5) Choose a template. 6) Preview and export as PDF."},
	{"ATS Optimization Feature", "product", "HiHired's AI analyzes your resume against the job description to identify missing keywords, optimize bullet points for ATS (Applicant Tracking Systems), and suggest improvements. It rewrites experience bullets with action verbs and quantified achievements that match the target role."},
	{"PDF Export and Templates", "product", "Export your resume as a professional PDF. Choose from multiple recruiter-approved templates. All templates are ATS-friendly and optimized for both human readability and automated screening systems."},
	{"Job Matching Feature", "product", "HiHired matches your resume against 35,000+ active job postings using AI-powered vector similarity search. You see a match score, skill fit percentage, matched and missing skills, and AI-generated reasons why each job fits your profile. Filter by location, remote type, and keywords."},
	{"One-Click AI Resume", "product", "The One-Click AI Resume feature takes a specific job match and automatically tailors your entire resume — experience bullets, projects, and summary — to match that job's requirements. It highlights your most relevant skills and rewrites content with the right keywords."},
	{"Application Tracking", "product", "Track your job applications with a Kanban-style dashboard. Drag and drop between stages: Applied, Screening, Interviewing, Offered, Accepted, Rejected, Withdrawn. Add notes, set reminders, and see your application pipeline at a glance."},
	{"AI Career Coach Chatbot", "product", "The AI chatbot can help with resume optimization, cover letter generation, interview preparation, salary negotiation advice, LinkedIn tips, and career guidance. It knows your resume data and can give personalized advice based on your background."},
	{"Account and Membership", "product", "Create a free account to save your resume data across sessions. Upgrade to Premium or Ultimate for more features. Manage your subscription from the Account page. Cancel anytime — your data is preserved."},
	{"Support and Contact", "product", "For help, use the chat widget or email hihired_support@tactechs.net. The team is Seattle-based and typically responds within 24 hours."},
	{"Data Privacy", "product", "HiHired stores your resume data securely. Your data is never shared with third parties or used to train AI models. You can delete your account and all associated data at any time."},
	{"Mobile Support", "product", "HiHired works on all devices — desktop, tablet, and mobile. Your resume progress is automatically saved and synced across devices."},
	{"Cover Letter Generation", "product", "Ask the AI chatbot to generate a cover letter. Provide a job description and the AI creates a personalized cover letter highlighting your relevant experience, skills, and motivation for the specific role."},
	{"Skill Gap Analysis", "product", "For each job match, HiHired shows which of your skills match the job requirements and which are missing. This helps you identify areas for improvement and prioritize which skills to develop or highlight."},

	// ── Resume Tips (15) ──────────────────────────────────
	{"How to Write a Professional Summary", "resume_tips", "A professional summary should be 2-3 sentences at the top of your resume. Lead with your years of experience and primary expertise. Mention 2-3 key skills or technologies. End with a notable achievement or career goal. Example: 'Senior software engineer with 7 years of experience building scalable distributed systems. Expert in Go, Kubernetes, and PostgreSQL. Led a team that reduced API latency by 40% serving 10M daily requests.'"},
	{"Action Verbs for Resume Bullets", "resume_tips", "Start every bullet point with a strong action verb. For technical roles: Architected, Built, Deployed, Engineered, Implemented, Integrated, Migrated, Optimized, Refactored, Scaled. For leadership: Directed, Led, Managed, Mentored, Spearheaded. For analysis: Analyzed, Assessed, Evaluated, Identified, Investigated. Avoid weak verbs like 'helped', 'assisted', 'worked on', 'was responsible for'."},
	{"How to Quantify Achievements", "resume_tips", "Replace vague statements with numbers. Instead of 'improved performance', write 'reduced page load time by 60% (from 5s to 2s)'. Instead of 'managed a team', write 'led a team of 8 engineers across 3 time zones'. Include metrics: revenue impact, cost savings, users served, uptime percentages, lines of code, response times, error rate reductions."},
	{"Skills Section Best Practices", "resume_tips", "Group skills by category: Languages (Python, Go, TypeScript), Frameworks (React, Django, Spring), Infrastructure (AWS, Kubernetes, Docker), Databases (PostgreSQL, Redis, MongoDB), Tools (Git, JIRA, Figma). List 10-20 relevant skills. Match skills exactly to the job description keywords. Don't include soft skills here — demonstrate them through experience bullets instead."},
	{"How to Handle Employment Gaps", "resume_tips", "Be honest about gaps. Use years instead of months to make small gaps less visible (2019-2021 instead of Jan 2019-Mar 2021). If you did anything productive during the gap, mention it: freelance work, courses, certifications, volunteering, personal projects. Address the gap in your cover letter if it's significant (6+ months)."},
	{"Resume Length Guidelines", "resume_tips", "1 page for 0-5 years experience. 2 pages for 5-15 years. 3 pages only for executives or academics. Quality over quantity — every line should earn its space. If you're cutting content, remove the oldest or least relevant experience first. Never go over 2 pages for a software engineering role."},
	{"ATS Keyword Optimization", "resume_tips", "ATS systems scan for exact keyword matches from the job description. Copy key phrases directly: if the JD says 'microservices architecture', use that exact phrase, not 'distributed systems'. Include both acronyms and full forms (AWS and Amazon Web Services). Use standard section headers (Experience, Education, Skills) — creative headers confuse ATS parsers."},
	{"Tailoring Your Resume for Each Job", "resume_tips", "Don't send the same resume to every job. For each application: 1) Read the job description carefully. 2) Identify the top 5 required skills/qualifications. 3) Reorder your experience bullets to highlight the most relevant ones first. 4) Add missing keywords from the JD. 5) Adjust your summary to match the role. HiHired's AI does this automatically with the One-Click feature."},
	{"Common Resume Mistakes", "resume_tips", "Top mistakes to avoid: 1) Typos and grammar errors (use a spell checker). 2) Including an objective statement instead of a summary. 3) Listing job duties instead of achievements. 4) Using personal pronouns (I, me, my). 5) Including a photo (in the US). 6) Using fancy fonts or colors that ATS can't parse. 7) Listing every technology you've ever touched. 8) Not including dates for experience entries."},
	{"Functional vs Chronological Resume Format", "resume_tips", "Chronological (most common): Lists experience in reverse chronological order. Best for consistent career progression. Functional: Groups experience by skill category. Use only if you have major gaps or are changing careers. Combination: Starts with a skills summary, then chronological experience. For most job seekers, chronological is safest because recruiters and ATS expect it."},
	{"How to List Certifications", "resume_tips", "Add certifications in your Skills section or a dedicated Certifications section. Include: certification name, issuing organization, and year obtained. Example: 'AWS Solutions Architect Associate (Amazon, 2024)'. Put the most relevant certifications first. Don't list expired certifications unless they're still widely recognized."},
	{"How to Format Education", "resume_tips", "For recent graduates: Education section goes near the top, include GPA if 3.5+, relevant coursework, honors. For experienced professionals: Education goes at the bottom, just school name, degree, field, and graduation year. Don't include high school if you have a college degree. Include relevant online courses or bootcamps if they're from recognized platforms."},
	{"Career Change Resume Tips", "resume_tips", "Highlight transferable skills — project management, data analysis, communication, leadership. Use a functional or combination format. Write a summary that bridges your old and new fields. Emphasize side projects, courses, or certifications in the new field. Show how your previous experience gives you a unique perspective."},
	{"Remote Work on Resumes", "resume_tips", "If you worked remotely, mention it: 'Remote' or 'Remote (US)' in the location field. Highlight remote-relevant skills: async communication, self-management, distributed team collaboration, time zone management. If the target job is remote, emphasize your remote work experience prominently."},
	{"Cover Letter vs Resume", "resume_tips", "Your resume lists facts (experience, skills, education). Your cover letter tells a story — why this company, why this role, why now. Don't repeat your resume in the cover letter. Instead, pick 2-3 achievements and explain the context and impact. Keep it under 400 words."},

	// ── Interview (10) ────────────────────────────────────
	{"STAR Method for Behavioral Interviews", "interview", "STAR stands for Situation, Task, Action, Result. For every behavioral question: Situation — set the context (when, where, what project). Task — what was your responsibility. Action — what specifically YOU did (not the team). Result — quantified outcome (saved $X, improved Y by Z%). Prepare 5-8 STAR stories covering: conflict resolution, leadership, failure, teamwork, tight deadline, ambiguity."},
	{"Common Behavioral Interview Questions", "interview", "Prepare answers for: 1) Tell me about a time you disagreed with your manager. 2) Describe a project that failed and what you learned. 3) How did you handle a tight deadline? 4) Give an example of leading without authority. 5) Tell me about a time you had to learn something quickly. 6) Describe your biggest professional achievement. 7) How do you handle ambiguity? 8) Tell me about a conflict with a coworker."},
	{"How to Answer Tell Me About Yourself", "interview", "Structure: Present → Past → Future. Present: 'I'm currently a senior engineer at X, focused on Y.' Past: 'Before that, I spent 3 years at Z building ABC.' Future: 'I'm excited about this role because it combines my experience in X with the opportunity to Y.' Keep it under 90 seconds. Don't recite your resume — tell a narrative."},
	{"Salary Negotiation Tips", "interview", "1) Never give a number first — ask for the range. 2) Research market rates on Levels.fyi, Glassdoor, and Blind. 3) Consider total compensation: base, bonus, equity, benefits, PTO. 4) Use competing offers as leverage (but don't bluff). 5) Negotiate after you receive the offer, not during interviews. 6) Ask for time to consider (24-48 hours is normal). 7) Be specific: 'Based on my research and experience, I'm targeting $X-Y.'"},
	{"How to Follow Up After an Interview", "interview", "Send a thank-you email within 24 hours. Address each interviewer by name. Reference something specific from your conversation. Keep it brief (3-4 sentences). If you haven't heard back after a week, send a polite follow-up asking about timeline. After two follow-ups with no response, move on but keep the door open."},
	{"Technical Interview Preparation", "interview", "For coding interviews: Practice on LeetCode/HackerRank (focus on medium difficulty). Know your data structures: arrays, trees, graphs, hash maps. Know algorithms: BFS/DFS, dynamic programming, sorting. For system design: Study distributed systems, databases, caching, load balancing. Practice with a friend or mock interview service. For behavioral: Prepare STAR stories."},
	{"How to Research a Company Before Interview", "interview", "1) Read the company's About page and recent blog posts. 2) Check Glassdoor for interview experiences and culture reviews. 3) Look at their tech blog for technology stack insights. 4) Check LinkedIn for the interviewer's background. 5) Read recent news/press releases. 6) Understand the product — sign up and try it if possible. 7) Prepare 2-3 thoughtful questions to ask."},
	{"Panel Interview Tips", "interview", "1) Make eye contact with everyone, not just the person who asked the question. 2) Address the questioner first, then scan the panel. 3) Remember names (write them down). 4) Ask the recruiter beforehand who will be on the panel and their roles. 5) Tailor examples to different panel members' areas (technical depth for engineers, business impact for managers)."},
	{"Phone Screen Best Practices", "interview", "1) Find a quiet location with good reception. 2) Have your resume and the job description in front of you. 3) Use a headset for clearer audio. 4) Stand up while talking (it improves voice energy). 5) Keep answers concise (1-2 minutes per question). 6) Prepare a brief intro and 2-3 questions to ask. 7) Smile while talking — it comes through in your voice."},
	{"How to Handle Rejection", "interview", "Rejection is normal — even strong candidates get rejected. 1) Ask for feedback (many companies will share it). 2) Don't take it personally — fit matters as much as skill. 3) Review what went well and what didn't. 4) Keep applying — the right match is out there. 5) Consider the rejection a data point, not a verdict. Average job search takes 3-6 months with 100+ applications."},

	// ── Career (5) ────────────────────────────────────────
	{"LinkedIn Profile Optimization", "career", "1) Professional headshot (65% more likely to be viewed). 2) Headline: not just your title — include specialties (e.g., 'Senior Backend Engineer | Go, Kubernetes, Distributed Systems'). 3) About section: 3 paragraphs — who you are, what you do, what you're looking for. 4) Featured section: link to projects, blog posts, or portfolio. 5) Skills: add 50 relevant skills and get endorsements. 6) Activity: post or comment weekly to increase visibility."},
	{"Networking Strategies for Job Seekers", "career", "1) Reach out to people at target companies via LinkedIn (not cold applying). 2) Attend virtual meetups and conferences in your field. 3) Ask for informational interviews, not jobs. 4) Follow up within 48 hours after meeting someone. 5) Give before you ask — share articles, make introductions, offer help. 6) Maintain your network even when not job searching."},
	{"Career Pivot Advice", "career", "1) Identify transferable skills from your current role. 2) Take courses or certifications in the new field (Coursera, bootcamps). 3) Build portfolio projects that demonstrate new skills. 4) Network with people already in the target field. 5) Consider a bridge role — a position that uses both old and new skills. 6) Be prepared to take a temporary step back in title/pay. 7) Frame your diverse background as a strength in interviews."},
	{"Job Search Timeline Expectations", "career", "Typical timeline: 1-2 weeks to update resume and LinkedIn. 2-4 weeks to start getting responses. 4-8 weeks for interview rounds. 1-2 weeks for offer and negotiation. Total: 2-4 months for most people. Apply to 5-10 jobs per week. Expect a 5-10% response rate. Track everything in a spreadsheet or application tracker. Don't get discouraged — it's a numbers game."},
	{"Working with Recruiters", "career", "1) Connect with specialized recruiters in your field (not just generalists). 2) Be honest about your timeline and salary expectations. 3) Recruiters work for the company, not you — they're helpful but represent the employer's interests. 4) Ask about the company culture, team size, and why the position is open. 5) You can work with multiple recruiters simultaneously. 6) If a recruiter ghosts you, move on — it happens frequently."},
}
