CREATE TABLE IF NOT EXISTS resume_skill_cache (
    resume_hash TEXT PRIMARY KEY,
    skills TEXT[] NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
