ALTER TABLE users ADD COLUMN IF NOT EXISTS followup_reminders_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS reminders_enabled BOOLEAN NOT NULL DEFAULT TRUE;
