name: Deploy to EC2

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.BACKEND_EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.BACKEND_EC2_SSH_KEY }}
        script: |
          cd ~/ai-resume-backend
          git pull origin main
          docker-compose -f docker-compose.backend.yml down
          docker-compose -f docker-compose.backend.yml build
          DB_HOST=${{ secrets.DB_HOST }} \
          DB_PORT=${{ secrets.DB_PORT }} \
          DB_NAME=${{ secrets.DB_NAME }} \
          DB_USER=${{ secrets.DB_USER }} \
          DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          DB_SSLMODE=${{ secrets.DB_SSLMODE }} \
          JWT_SECRET=${{ secrets.JWT_SECRET }} \
          docker-compose -f docker-compose.backend.yml up -d
          docker system prune -f 